browser:
  directConnect: true
  seleniumAddress: false
  seleniumServerJarPath: '../../../node_modules/webdriver-manager/selenium/selenium-server-standalone-3.*.jar'
  chromeDriverPath: "../../../node_modules/webdriver-manager/selenium/chromedriver_2.*"
  firefoxPath:
  width: 200
  height: 750

timeouts:
  allScriptsTimeout: 30000
  getPageTimeout: 30000
  defaultTimeoutInterval: 30000

framework: 'jasmine'
